insert into students values ('alex6223', 3, 'Alexander Lihn Mikkelsen');
insert into students values ('alex213c', 1, 'Alexander Sørensen');
insert into students values ('alex7915', 2, 'Alexander Vestergaard Jakobsen');
insert into students values ('ande623i', 2, 'Anders Dollas Hansen');
insert into students values ('ande145c', 1, 'Anders Ladefoged Rosenven Østergaard');
insert into students values ('ande817s', 3, 'Anders Møller Andersen');
insert into students values ('andr687w', 3, 'Andreas Boll Nielsen');
insert into students values ('andr9153', 1, 'Andreas Clement Larsen');
insert into students values ('andr791d', 2, 'Andreas Dideriksen');
insert into students values ('anto6789', 3, 'Anton John Erik Sundström');
insert into students values ('boxx8892', 1, 'Bo Mandsholm Saurbrey Lundstedt');
insert into students values ('casp6976', 1, 'Casper Ryttergaard Vindum');
insert into students values ('chri837r', 2, 'Chris Ishøj Lang Sørensen');
insert into students values ('chri45i4', 3, 'Christian Frederik Bøgh');
insert into students values ('chri70ec', 2, 'Christian Tilgreen Mogensen');
insert into students values ('chri50h7', 2, 'Christoffer Skovgaard Hansen');
insert into students values ('dani951g', 2, 'Daniel Lorenz Taaning Rasmussen');
insert into students values ('dani479g', 3, 'Daniel Nygaard Vuust');
insert into students values ('dani92a5', 3, 'Daniel Skafte Nielsen');
insert into students values ('fred842h', 2, 'Frederik Hallgren Holmquist');
insert into students values ('fred19h3', 3, 'Frederik P Nielsen');
insert into students values ('gust2488', 2, 'Gustav Beck Petersen');
insert into students values ('hjal0759', 2, 'Hjalte Villum Laksafoss');
insert into students values ('jamm0008', 1, 'Jammie Jackson Gay Washo');
insert into students values ('jepp6960', 3, 'Jeppe Dehli Sørensen');
insert into students values ('jesp446c', 3, 'Jesper Klejs Deleurand');
insert into students values ('joac3146', 3, 'Joachim Norup Hansen');
insert into students values ('jona810j', 3, 'Jonas Rasmussen');
insert into students values ('jona834f', 1, 'Jonatan Emil Sørensen');
insert into students values ('kasp609g', 3, 'Kasper Rindom Jeppesen');
insert into students values ('katr8787', 1, 'Katrine Jensen');
insert into students values ('kenn229k', 3, 'Kenneth Andersen');
insert into students values ('kent3211', 3, 'Kent Brian Richardt Pedersen');
insert into students values ('kris319d', 3, 'Kristoffer Rasmus Nielsen');
insert into students values ('lass932m', 2, 'Lasse Andersen');
insert into students values ('lass9810', 2, 'Lasse Jonas Jensen');
insert into students values ('lyne0018', 1, 'Lyneth Cagande Jensen');
insert into students values ('mads327e', 2, 'Mads Arpe-Strøm');
insert into students values ('mads379m', 3, 'Mads Emil Stasel');
insert into students values ('mads303n', 2, 'Mads Midtgaard Christiansen');
insert into students values ('marc8847', 3, 'Marcus Damgaard Bournonwille');
insert into students values ('marc7075', 3, 'Marcus Jensen');
insert into students values ('mark311c', 2, 'Mark Hvidtfeldt');
insert into students values ('mart740q', 1, 'Martin Elvig Johansson');
insert into students values ('mart112f', 3, 'Martin Riehn Madsen');
insert into students values ('math675b', 2, 'Mathias Dahlgren Nymann');
insert into students values ('mehd0117', 1, 'Mehdi Nasseri');
insert into students values ('mich612i', 3, 'Michael Gotfredsen Jakobsen');
insert into students values ('mikk4212', 2, 'Mikkel Holm Kristiansen');
insert into students values ('mort659d', 1, 'Morten Andresen');
insert into students values ('nick3529', 2, 'Nicklas Phillip Gulddal');
insert into students values ('nico9551', 1, 'Nicolai Møgelgaard Raahauge');
insert into students values ('patr371f', 3, 'Patrick Heesch');
insert into students values ('patr7243', 1, 'Patrick Jensen');
insert into students values ('pete646a', 1, 'Peter Bøgh Stubberup');
insert into students values ('phil313a', 1, 'Philip Blander Sørensen');
insert into students values ('rose1184', 1, 'Rosemarie Joy Ledesma-Broholm');
insert into students values ('seba6474', 3, 'Sebastian Lind Karlsen');
insert into students values ('seba8769', 2, 'Sebastian Palm');
insert into students values ('simo132h', 1, 'Simon Winkel');
insert into students values ('stef8464', 2, 'Stefan Johansson Toft');
insert into students values ('sune1275', 2 , 'Sune Ålsbøl Brandt');
insert into students values ('teom0002', 3, 'Teo');
insert into students values ('thom09r7', 3, 'Thomas Carl Alexander Dänhardt');
insert into students values ('tobi3686', 3, 'Tobias Rosenvinge. Hammer.');
insert into students values ('vict4465', 1, 'Vikctor Emil Astrup Madsen');